### ISSUE TITLE
Authentication Task

### ISSUE THREAD

**Issue by alvinmarshall** [wamiikechukwu/Learning#2]
Create This class with issue name in usecase package #1 
constructor should have IUserRepository as paramter #1 

### Fields
1. Username
1. Password

### Repository
- [x] add login(above field) method to Repository interface
- [x] login should return user object #1 

### Unit test
- [x] should get authorized user data (the user object created in #1)
- [x] should throw an exception when user data is null

**Comment by wamiikechukwu** [comment]
All Unit Test passed, created a pull request
