### ISSUE TITLE
UserRepository

### ISSUE THREAD

**Issue by alvinmarshall** [wamiikechukwu/Learning#3]
Create this class with issue name in repository package
Create an interface with name **UserDao** in package db/dao

### NB
Remember that userDao is from room, but **don't** annotate it yet

### UserDao
- [x] add **saveUser** method with paramter User object #1
- [x] add **getUser** method with paramter {**username**,**password**}   which returns User object

- [x] implement IUserRepository #1 in this class
- [x] constructor should have **userDao** as a paramter

### Unit test
- [x] should save user with **user** entity
- [x] should get user with {**username**,**password**}

**Comment by wamiikechukwu** [comment]
Successfully passed unit testing...
